main_mt: math.ml list_aux.mli list_aux.ml geom.ml render.ml main_mt.ml
	ocamlopt.opt math.ml list_aux.mli list_aux.ml geom.ml render.ml main_mt.ml -o main_mt

main_st: math.ml list_aux.mli list_aux.ml geom.ml render.ml main.ml
	ocamlopt.opt math.ml list_aux.mli list_aux.ml geom.ml render.ml main.ml -o main_st
